package test.mvn.level2;

import oracle.jbo.server.ApplicationModuleImpl;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 27 23:40:27 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DemoLevel2AppModuleImpl extends ApplicationModuleImpl {
    public static final Logger log = LogManager.getLogger();
    /**
     * This is the default constructor (do not remove).
     */
    public DemoLevel2AppModuleImpl() {
    }
    
    public String testDemo2(String param) {
        return "Ok2 - " + param;
    }
}

