package test.mvn.level1;

import oracle.jbo.server.ApplicationModuleImpl;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import test.mvn.level1.common.DemoLevel1AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 27 22:33:29 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DemoLevel1AppModuleImpl extends ApplicationModuleImpl implements DemoLevel1AppModule {
    public static final Logger log = LogManager.getLogger();
    /**
     * This is the default constructor (do not remove).
     */
    public DemoLevel1AppModuleImpl() {
    }
    
    public String testLevel1(String param) {
        log.debug("recv param: {}", param);
        return "OK - " + param;
    }
}

