package test.mvn.level1.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 27 23:33:17 EEST 2016
// ---------------------------------------------------------------------
public interface DemoLevel1AppModule extends ApplicationModule {
    String testLevel1(String param);
}

